spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ozerp_db?createDatabaseIfNotExist=true
    username: root
    password: Chevron@6
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: ture
    properties:
      hibernate:
        format-sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL57Dialect
