spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ozerp_db?createDatabaseIfNotExist=true
    username: root
    password: Chevron@6
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL57Dialect

jwt:
  secret: 123BGTH_ujjh65gftbg5egjerg!!345*(&8nfnfhrt4gdds)))9-deddhty523)98___)87543..6r4
  expiration: 86400000
  tokenPrefix: Bearer
  headerString: Authorization